/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package atm_wizard_3142831;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Abdul Aziz Kalsekar
 */
public class UserDetails extends javax.swing.JFrame {

    /**
     * Creates new form UserDetails
     */
    public UserDetails() {
        initComponents();
    }
  String accno, accBalance,name;
    public UserDetails(String a) {
        initComponents();
        
        accno = a;
        accNumText.setText(accno);
        
        String AccountNumber;
        try 
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/atm", "root","0000");
            
            AccountNumber = accno;
            
            Statement st = con.createStatement();
            String query = "SELECT * FROM atm_data where (AccountNo) = ("+AccountNumber+");";
            ResultSet rs = st.executeQuery(query);
            
            if(rs.next())
            {
                String Name = String.valueOf(rs.getString("Name"));
                String Balance = String.valueOf(rs.getString("Balance"));
                nameText.setText(Name);
                balanceText.setText(Balance);
            }
          
        } 
        catch (ClassNotFoundException ex) 
        {
            Logger.getLogger(UserDetails.class.getName()).log(Level.SEVERE, null, ex);
        } 
        catch (SQLException ex) 
        {
            Logger.getLogger(UserDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        withdrawWithRBtn = new java.awt.Button();
        accNumText = new java.awt.TextField();
        accNameLBl = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        nameText = new java.awt.TextField();
        balanceText = new java.awt.TextField();
        accNameLBl1 = new java.awt.Label();
        label2 = new java.awt.Label();
        accNameLBl2 = new java.awt.Label();
        wAmountBox = new javax.swing.JComboBox<>();
        withdrawWithoutRBtn = new java.awt.Button();
        abortBtn = new java.awt.Button();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label1.setName(""); // NOI18N
        label1.setText("Account Details");

        withdrawWithRBtn.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        withdrawWithRBtn.setLabel("Withdraw money with reciept");
        withdrawWithRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawWithRBtnActionPerformed(evt);
            }
        });

        accNameLBl.setText("Account no:");

        label3.setText("Name:");

        label4.setText("Balance:");
        label4.setVisible(false);

        nameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextActionPerformed(evt);
            }
        });

        balanceText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balanceTextActionPerformed(evt);
            }
        });

        accNameLBl1.setText("Balance amount:");

        label2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label2.setName(""); // NOI18N
        label2.setText("Withdraw Money");

        accNameLBl2.setText("Withdraw Amount:");

        wAmountBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "10", "20", "30", "40", "50", "60", "70", "80", "90", "100", "110", "120", "130", "140", "150", "160", "170", "180", "190", "200", "210", "220", "230", "240", "250", " ", " " }));

        withdrawWithoutRBtn.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        withdrawWithoutRBtn.setLabel("Withdraw money without reciept");
        withdrawWithoutRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawWithoutRBtnActionPerformed(evt);
            }
        });

        abortBtn.setBackground(new java.awt.Color(240, 0, 0));
        abortBtn.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        abortBtn.setLabel("Abort transaction");
        abortBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abortBtnActionPerformed(evt);
            }
        });

        label5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label5.setText("£");

        label6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label6.setName(""); // NOI18N
        label6.setText("€");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel1.setText("(Please select your amount here)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(accNameLBl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nameText, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                    .addComponent(accNumText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(abortBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(accNameLBl1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accNameLBl2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(balanceText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(withdrawWithRBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(wAmountBox, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1))
                            .addComponent(withdrawWithoutRBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(59, 59, 59))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(accNameLBl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(accNumText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(accNameLBl1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(balanceText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(wAmountBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1))))
                            .addComponent(accNameLBl2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addComponent(withdrawWithRBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(abortBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(withdrawWithoutRBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        label3.getAccessibleContext().setAccessibleName("");
        label2.getAccessibleContext().setAccessibleName("");
        abortBtn.getAccessibleContext().setAccessibleName("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextActionPerformed

    private void abortBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abortBtnActionPerformed
        // TODO add your handling code here:
       this.dispose();
       new Complete().setVisible(true);
    }//GEN-LAST:event_abortBtnActionPerformed

    private void withdrawWithRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawWithRBtnActionPerformed
        // TODO add your handling code here:
        double a= wAmountBox.getSelectedIndex();
        double c= a*10;
        String selectAmt= Integer.toString(wAmountBox.getSelectedIndex());
        Double b= Double.parseDouble(balanceText.getText());
        accno = accNumText.getText();
        name= nameText.getText();
        
        if(selectAmt.equals("0"))
        {
            JOptionPane.showMessageDialog(this, "The amount to withdraw has not been selected!");
        }
        else
        {
            if(b<c)
            {
                JOptionPane.showMessageDialog(this, "You have insufficient balance!");
            }
            else
            {
                double Balance=b-(c*0.82);
                try 
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/atm", "root","0000");
            
            Statement st = con.createStatement();
            String query = "SELECT * FROM atm_data where (AccountNo) = ("+accno+");";
            Statement st3 = con.createStatement();
            String query3 = "INSERT INTO atm_data2 () VALUES ('"+accno+"', '"+name+"', '"+Balance+"', '"+c+"')";
            ResultSet rs = st.executeQuery(query);
            
            if(rs.next())
            {
                Statement st2 = con.createStatement();
                String query2 = "UPDATE atm_data SET Balance = ("+Balance+") WHERE (AccountNo) = ("+accno+");";
                st2.executeUpdate(query2);
                st3.executeUpdate(query3);
                
                balanceText.setText(Double.toString(Balance));
                JOptionPane.showMessageDialog(null,"Name: "+name+"\nAccount No: "+accno+"\nAmount Withdrawn(in €): "+c+"\nNew Balance(in £): "+Balance+"", "Reciept", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
                new Complete().setVisible(true);
      
            }
         
        } 
        catch (ClassNotFoundException ex) 
        {
            Logger.getLogger(UserDetails.class.getName()).log(Level.SEVERE, null, ex);
        } 
        catch (SQLException ex) 
        {
            Logger.getLogger(UserDetails.class.getName()).log(Level.SEVERE, null, ex);
        }

            }
        }
    }//GEN-LAST:event_withdrawWithRBtnActionPerformed

    private void withdrawWithoutRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawWithoutRBtnActionPerformed
        // TODO add your handling code here:
        
        double a= wAmountBox.getSelectedIndex();
        double c= a*10;
        String selectAmt= Double.toString(a);
        Double b= Double.parseDouble(balanceText.getText());
        accno = accNumText.getText();
        name= nameText.getText();
        
        if(selectAmt.equals("0"))
        {
            JOptionPane.showMessageDialog(this, "The amount to withdraw has not been selected!");
        }
        else
        {
            if(b<c)
            {
                JOptionPane.showMessageDialog(this, "You have insufficient balance!");
            }
            else
            {
                double Balance=b-(c*0.82);
                try 
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/atm", "root","0000");
            
            Statement st = con.createStatement();
            String query = "SELECT * FROM atm_data where (AccountNo) = ("+accno+");";
            Statement st3 = con.createStatement();
            String query3 = "INSERT INTO atm_data2 (`AccountNo`, `Name`, `Balance`, `WithdrawAmount`) VALUES ('"+accno+"', '"+name+"', '"+Balance+"', '"+c+"')";
           
            //Statement st2 = con.createStatement();
            //String query2 = "SELECT * FROM atm_data where;";
            ResultSet rs = st.executeQuery(query);
            
            if(rs.next())
            {
                Statement st2 = con.createStatement();
                String query2 = "UPDATE atm_data SET Balance = ("+Balance+") WHERE (AccountNo) = ("+accno+");";
                st2.executeUpdate(query2);
                st3.executeUpdate(query3);
                balanceText.setText(Double.toString(Balance));
                this.dispose();
                new Complete().setVisible(true);
      
            }

        } 
        catch (ClassNotFoundException ex) 
        {
            Logger.getLogger(UserDetails.class.getName()).log(Level.SEVERE, null, ex);
        } 
        catch (SQLException ex) 
        {
            Logger.getLogger(UserDetails.class.getName()).log(Level.SEVERE, null, ex);
        }

            }
        }
    }//GEN-LAST:event_withdrawWithoutRBtnActionPerformed

    private void balanceTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balanceTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_balanceTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button abortBtn;
    private java.awt.Label accNameLBl;
    private java.awt.Label accNameLBl1;
    private java.awt.Label accNameLBl2;
    private java.awt.TextField accNumText;
    private java.awt.TextField balanceText;
    private javax.swing.JLabel jLabel1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.TextField nameText;
    private javax.swing.JComboBox<String> wAmountBox;
    private java.awt.Button withdrawWithRBtn;
    private java.awt.Button withdrawWithoutRBtn;
    // End of variables declaration//GEN-END:variables
}
